name=Grefur_Module_Driver
version=1.0.0
author=grefur AS
maintainer=grefur AS
sentence=Core driver for grefur I2C slave sensor nodes.
paragraph=Enables plug-and-play sensor discovery and live data streaming via the grefur protocol.
category=Communication
url=https://grefur.no
architectures=*
